### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by firba1** [salesforce-python-client/pyforce#37]
Python 2.7 has less than [a year](pythonclock.org) left of official support. This library should support python 3.

**Comment by idbentley** [comment]
This project is not actively developed anymore.  You would do well to adopt it if you plan on relying on it for anything.

**Comment by alanjcastonguay** [comment]
Project is free to good home.

**Comment by ViViDboarder** [comment]
@alanjcastonguay thoughts on migrating this to a GitHub org? I'd be happy to try and manage some of this migration.

**Comment by alanjcastonguay** [comment]
Sure. You have a name in mind?

(Would probably need to change out TravisCI credentials too.)

**Comment by idbentley** [comment]
Would doing so mean losing open source access to this code?

I know it's outdated, but it's still useful.

**Comment by alanjcastonguay** [comment]
I wouldn't expect so, no.

**Comment by ViViDboarder** [comment]
I would expect a public org. It’s just an easier way to manage it because you can assign different people as owners.

As for name, maybe pyforce? So pyforce/pyforce?

**Comment by ViViDboarder** [comment]
Bump. Thoughts?

**Comment by alanjcastonguay** [comment]
Ack; naming things is hard. That sounds fine.
