### ISSUE TITLE
Hand control of PyPI project to the Org

### ISSUE THREAD

**Issue by alanjcastonguay** [salesforce-python-client/pyforce#39]
https://pypi.org/project/pyforce/ is in @alanjcastonguay 's personal PyPI account. 

Reduce bus factor. Make it controllable by all org members.

**Comment by alanjcastonguay** [comment]
Todo: How? @ViViDboarder

**Comment by alanjcastonguay** [comment]
https://pypi.org/manage/project/pyforce/collaboration/

I'll need the PyPI username of each target user, including @ViViDboarder

**Comment by ViViDboarder** [comment]
@alanjcastonguay sorry for the delay. My Pypi username is vividboarder.

**Comment by alanjcastonguay** [comment]
@ViViDboarder added you to https://pypi.org/manage/project/pyforce/collaboration/ as an Owner. Use your power for good, not evil.
