### ISSUE TITLE
Change pypi credentials in .travis.yml ?

### ISSUE THREAD

**Issue by alanjcastonguay** [salesforce-python-client/pyforce#41]
`.travis.yaml` encodes a release step pushing to pypi, using @alanjcastonguay credentials. The password there is encrypted and isn't used for anything else. As far as I know that still works.

What's the best practice here? Should the credentials be replaced with that of another human? A machine-account with only Maintainer rights?

**Comment by ViViDboarder** [comment]
This is a good question that I don't have a good answer to. Probably the latter?

**Comment by alanjcastonguay** [comment]
I received and approved your TravisCI binding request

**Comment by ViViDboarder** [comment]
Oh, and I answered the question. You can create an API token that is scoped for this very purpose. I'll try to update it in Travis. If not, I can set up a Github Action workflow.

**Comment by ViViDboarder** [comment]
For some reason I couldn't get Travis to actually try and run the deploy. I ended up adding a gh action instead.

**Comment by ViViDboarder** [comment]
Oh, looks like whatever I did to get the Github Workflow to work also fixed Travis deploying. I suppose we can drop the Travis build now that the Github one is using an API Token rather than user credentials.
